FROM cgr.dev/chainguard/python:latest-dev as dev

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --user --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /app

COPY app.py .
COPY templates templates/
COPY static static/
ENV REDIS_HOST="192.168.15.60"
COPY --from=dev /home/nonroot/.local/lib/python3.14/site-packages /home/nonroot/.local/lib/python3.14/site-packages
COPY --from=dev /home/nonroot/.local/bin/flask /app/flask

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]